In [1]:
import os
import pandas as pd
import json

In [25]:
# Set the path to your Chrome bookmarks file
bookmarks_path = os.path.join(os.environ['HOME'], 'Library', 'Application Support', 'Google', 'Chrome', 'Default', 'Bookmarks')
bookmarks_path

'/Users/adityaagarwal/Library/Application Support/Google/Chrome/Default/Bookmarks'

In [26]:
# Load the bookmarks file
with open(bookmarks_path, 'r') as f:
    bookmarks = json.load(f)

In [30]:
# Set the name of the folder you're interested in
folder_name = 'SQL'


# Initialize an empty list to store the bookmarks
bookmarks_list = []
# Function to recursively traverse the bookmarks tree
def traverse_bookmarks(bookmarks, folder_name):
    for bookmark in bookmarks:
        if bookmark['type'] == 'folder' and bookmark['name'] == folder_name:
            for child in bookmark['children']:
                if 'url' in child:
                    bookmarks_list.append({
                        'Title': child['name'],
                        'URL': child['url']
                    })
        elif 'children' in bookmark:
            traverse_bookmarks(bookmark['children'], folder_name)

In [31]:
# Traverse the bookmarks tree
traverse_bookmarks(bookmarks['roots']['bookmark_bar']['children'], folder_name)

# Create a pandas dataframe from the bookmarks list
df = pd.DataFrame(bookmarks_list)
df

,Title,URL
0,Ultimate SQL Interview Guide For Data Scientis...,https://datalemur.com/blog/sql-interview-guide...
1,SQL-Interview-Prep-Question,https://github.com/Aafreen29/SQL-Interview-Pre...
2,The SQL Tutorial for Data Analysis | Basic SQL...,https://mode.com/sql-tutorial/introduction-to-...
3,SQLZoo,https://sqlzoo.net/wiki/SQL_Tutorial
4,"SQL SUBQUERIES - Exercises, Practice, Solution...",https://www.w3resource.com/sql-exercises/subqu...
5,30 Days of SQL - From Basic to Advanced Level!...,https://www.geeksforgeeks.org/30-days-of-sql-f...
6,8 Week SQL Challenge – Start your SQL learning...,https://8weeksqlchallenge.com/
7,Home | Oracle Cloud Infrastructure,https://cloud.oracle.com/?region=us-sanjose-1&...
8,SQL Virtual Practice | DB Fiddle,https://www.db-fiddle.com/
9,SQL Short Reads | SQL PRACTICE PROBLEMS,https://sqlshortreads.com/sql-practice-problems/
10,SQL Interview Questions With Examples | Clever...,https://thecleverprogrammer.com/2023/07/19/sql...
11,Learn SQL - Online SQL Terminal - Practice SQL...,https://www.sql-practice.com/
12,Text to SQL | PartyRock,https://partyrock.aws/u/viktoria/Kc0cM7_b-/Tex...
13,SQL-Projects/data-lemur.sql at main · ashrutro...,https://github.com/ashrutrode/SQL-Projects/blo...
14,Next Level SQL,https://www.nextlevelsql.com/home

In [29]:
df

                           Title                                  URL
0                      daily.dev               https://app.daily.dev/
1           Towards Data Science      https://towardsdatascience.com/
2                 DataCamp Blogs        https://www.datacamp.com/blog
3  Read Articles for free | 12ft                     https://12ft.io/
4                        Twitter             https://twitter.com/home
5                         Reddit              https://www.reddit.com/
6                          Blind           https://www.teamblind.com/
7       Machine Learning Mastery  https://machinelearningmastery.com/

In [32]:
bookmarks

{'checksum': 'a1d21b5bbbad2b91473d430cae84c7a9',
 'roots': {'bookmark_bar': {'children': [{'children': [{'date_added': '13358709420155515',
       'date_last_used': '13365796532388224',
       'guid': '98795267-d3f7-4b71-88eb-99bb6a46006d',
       'id': '1241',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'daily.dev',
       'type': 'url',
       'url': 'https://app.daily.dev/'},
      {'date_added': '13359173511730372',
       'date_last_used': '0',
       'guid': '0a7afbe9-7028-42d6-8361-28a051bf934d',
       'id': '1245',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Towards Data Science',
       'type': 'url',
       'url': 'https://towardsdatascience.com/'},
      {'date_added': '13359173835208741',
       'date_last_used': '13361744796143047',
       'guid': 'd15c84ad-f82e-42ba-a085-67b1604263da',
       'id': '1246',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'DataCamp Blogs',
       'type': 'url',
       'url': 'https://www.datacamp.com/blog'},
      {'date_added': '13357770220633947',
       'date_last_used': '13365637194552595',
       'guid': 'b0d931af-988b-4ee8-a191-e145683d50e4',
       'id': '1228',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Read Articles for free | 12ft',
       'type': 'url',
       'url': 'https://12ft.io/'},
      {'date_added': '13361744937551408',
       'date_last_used': '13365796547083008',
       'guid': '31001b85-2435-4695-a98c-4fbbd788a4f4',
       'id': '1262',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Twitter',
       'type': 'url',
       'url': 'https://twitter.com/home'},
      {'date_added': '13361744946622437',
       'date_last_used': '0',
       'guid': 'f918de93-0d39-40eb-b73b-0a4dd3e30db3',
       'id': '1261',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Reddit',
       'type': 'url',
       'url': 'https://www.reddit.com/'},
      {'date_added': '13361744974287340',
       'date_last_used': '13366158708717216',
       'guid': 'f9a3c13c-53fc-4761-984c-601db1ac21cf',
       'id': '1263',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Blind',
       'type': 'url',
       'url': 'https://www.teamblind.com/'},
      {'date_added': '13362533463445302',
       'date_last_used': '0',
       'guid': 'fe3647ce-4a9c-4f35-ba47-83f9bd13873a',
       'id': '1267',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Machine Learning Mastery',
       'type': 'url',
       'url': 'https://machinelearningmastery.com/'}],
     'date_added': '13361744846432243',
     'date_last_used': '0',
     'date_modified': '13362533463445302',
     'guid': 'f0966d31-0374-4258-bd58-eab959777b18',
     'id': '1260',
     'name': 'News',
     'type': 'folder'},
    {'children': [{'date_added': '13365961165876533',
       'date_last_used': '0',
       'guid': '82ed80e7-6021-4147-864e-973192c7ec04',
       'id': '1293',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'GPTZero',
       'type': 'url',
       'url': 'https://gptzero.me/'},
      {'date_added': '13365961234060094',
       'date_last_used': '0',
       'guid': 'b3b8b137-9db5-4491-af2e-ab83de1198d7',
       'id': '1292',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Bypass AI (Free)',
       'type': 'url',
       'url': 'https://bypass.hix.ai/'},
      {'date_added': '13365961623972167',
       'date_last_used': '0',
       'guid': 'c6a40651-fedb-4703-85ee-b68715fa4bc5',
       'id': '1291',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'GPRM : GitHub Profile ReadMe Maker',
       'type': 'url',
       'url': 'https://gprm.itsvg.in/'},
      {'date_added': '13366754118834090',
       'date_last_used': '0',
       'guid': '2b9b0dd4-8535-4136-9b3d-9efd1d3d0209',
       'id': '1306',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Meta AI',
       'type': 'url',
       'url': 'https://www.meta.ai/'}],
     'date_added': '13365961186531728',
     'date_last_used': '0',
     'date_modified': '13366754125267675',
     'guid': 'd273b3c0-f336-46c4-b2cd-024d3f018ad5',
     'id': '1290',
     'name': 'AI',
     'type': 'folder'},
    {'children': [{'date_added': '13344727664098038',
       'date_last_used': '13360969475496139',
       'guid': '110d7bcc-d2b0-4ccd-9bf1-4afc55ad7189',
       'id': '1159',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Leetcode Alternative | LintCode',
       'type': 'url',
       'url': 'https://www.lintcode.com/'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': '8222ea8f-1a5b-44d8-9b16-c570ac474110',
       'id': '41',
       'name': 'Microsoft Courses | Browse All',
       'type': 'url',
       'url': 'https://docs.microsoft.com/en-us/learn/browse/?terms=data%20ana'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': 'c45ec322-bd9d-4fcf-bdd8-94eb73a8eb29',
       'id': '43',
       'name': 'Coursera | Online Courses',
       'type': 'url',
       'url': 'https://www.coursera.org/'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': '5205c8c2-aef2-47ed-a9c6-2a5b8c837d9e',
       'id': '44',
       'name': 'FreeCodeCamp | Learn to Code - For Free',
       'type': 'url',
       'url': 'https://www.freecodecamp.org/learn/'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': 'eaa90194-4113-4080-9818-89c62199b9e8',
       'id': '45',
       'name': 'EDX | Dashboard',
       'type': 'url',
       'url': 'https://courses.edx.org/dashboard'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': 'a04cec57-657e-454f-87dd-dfc5ac11458b',
       'id': '46',
       'name': 'HackerRank | Dashboard',
       'type': 'url',
       'url': 'https://www.hackerrank.com/dashboard'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': '174eb989-a769-4c4d-b93a-adc72b23f585',
       'id': '47',
       'name': 'LeetCode',
       'type': 'url',
       'url': 'https://leetcode.com/'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': 'bb29dece-6392-4eca-9433-e07e78f97c51',
       'id': '48',
       'name': 'HackerEarth.com',
       'type': 'url',
       'url': 'https://www.hackerearth.com/practice/'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': '38430739-2218-425d-aa4d-f45b5c474855',
       'id': '110',
       'name': 'Online Programming Courses | Harvard University',
       'type': 'url',
       'url': 'https://online-learning.harvard.edu/subject/programming'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': 'b9f4a58a-0fae-4a5f-b27e-93fe24251e46',
       'id': '50',
       'name': 'MIT Free Online Course Materials',
       'type': 'url',
       'url': 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/'},
      {'date_added': '13270988325000000',
       'date_last_used': '0',
       'guid': 'f6145559-cebd-4de4-881a-749fd7db4df0',
       'id': '51',
       'name': 'MIT Open Learning brings Online Learning to MIT and the world',
       'type': 'url',
       'url': 'https://openlearning.mit.edu/'},
      {'date_added': '13290488671401734',
       'date_last_used': '13359753772669468',
       'guid': 'fa244512-126a-455d-a8e9-55b8b496be6d',
       'id': '512',
       'name': 'nbviewer | Sharing ipynb with GitHub',
       'type': 'url',
       'url': 'https://nbviewer.org/'},
      {'date_added': '13296191403126495',
       'date_last_used': '0',
       'guid': 'f151b51d-df36-4532-bc76-fd1799f39148',
       'id': '554',
       'name': 'Google Learning Paths | Google Cloud Skills Boost',
       'type': 'url',
       'url': 'https://www.cloudskillsboost.google/paths'},
      {'date_added': '13296884014202333',
       'date_last_used': '0',
       'guid': 'b8268b26-ed13-431c-81f8-0f5a9377fbbb',
       'id': '587',
       'name': 'Simplilearn - Resources',
       'type': 'url',
       'url': 'https://www.simplilearn.com/resources'},
      {'date_added': '13308552581394708',
       'date_last_used': '0',
       'guid': '01a8add3-5bac-44e1-b5da-f96935e044be',
       'id': '711',
       'name': 'Analytics Vidhya Courses',
       'type': 'url',
       'url': 'https://courses.analyticsvidhya.com/enrollments'},
      {'date_added': '13352920463100491',
       'date_last_used': '13359753822655980',
       'guid': '2346eb37-6e54-4c24-b16d-5ca02b9d3c14',
       'id': '1176',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'GitHub For interview questions',
       'type': 'url',
       'url': 'https://archive.org/details/github.com-DopplerHQ-awesome-interview-questions_-_2021-04-28_08-52-07'},
      {'date_added': '13317363564431620',
       'date_last_used': '0',
       'guid': '099b9198-e6f3-47d0-89a5-25363e4ccaf6',
       'id': '777',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'arXiv.org | Research Papers List',
       'type': 'url',
       'url': 'https://arxiv.org/'},
      {'date_added': '13355701064766528',
       'date_last_used': '0',
       'guid': 'ebd5b707-2c3a-4abc-875f-38f0ac2f8442',
       'id': '1191',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Carbon | Create Code Snippets',
       'type': 'url',
       'url': 'https://carbon.now.sh/'},
      {'date_added': '13355769541081581',
       'date_last_used': '0',
       'guid': '518eed99-bc46-42d0-88dc-0197c12b044e',
       'id': '1190',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Airtable',
       'type': 'url',
       'url': 'https://airtable.com/'},
      {'date_added': '13356307849558122',
       'date_last_used': '0',
       'guid': '9e6b0de5-ecbb-42cb-a382-3ebef1b9c26a',
       'id': '1213',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Deep Learning Online Courses | NVIDIA',
       'type': 'url',
       'url': 'https://www.nvidia.com/en-us/training/online/'},
      {'date_added': '13356412060030204',
       'date_last_used': '13360977301691423',
       'guid': 'b50cf60e-5927-4996-85ec-54e57bd95193',
       'id': '1212',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Explore | Infosys Springboard',
       'type': 'url',
       'url': 'https://infosysspringboard.ausnz.onwingspan.com/web/en/page/explore'},
      {'date_added': '13359505664536829',
       'date_last_used': '13361027742315267',
       'guid': '3ce13ccc-5141-4c70-be39-54822a7c59e7',
       'id': '1248',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'DataScience Portfolio.Io',
       'type': 'url',
       'url': 'https://www.datascienceportfol.io/'},
      {'date_added': '13361147367144813',
       'date_last_used': '0',
       'guid': '99e4dd6f-b32b-4611-a36d-c3963e162f5a',
       'id': '1264',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Alg & DS | Visualize Code',
       'type': 'url',
       'url': 'https://memlayout.com/algorithms-and-data-structures'},
      {'date_added': '13361147373545399',
       'date_last_used': '0',
       'guid': '203efee1-fc8d-436a-b03f-0953ec7cf5d1',
       'id': '1265',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'DSA via animation | VisuAlgo',
       'type': 'url',
       'url': 'https://visualgo.net/en'},
      {'date_added': '13362961690185691',
       'date_last_used': '0',
       'guid': 'a9789f54-1848-45a8-b70e-3789d2bb2afc',
       'id': '1270',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'AWS Skill Builder',
       'type': 'url',
       'url': 'https://explore.skillbuilder.aws/learn'},
      {'date_added': '13365551775145165',
       'date_last_used': '0',
       'guid': '0d3d3a73-48d3-4691-800a-1c4e8ef74f04',
       'id': '1286',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Linktree Admin',
       'type': 'url',
       'url': 'https://linktr.ee/admin'}],
     'date_added': '13276213311957564',
     'date_last_used': '0',
     'date_modified': '13365562023139862',
     'guid': '26f640cc-d46e-485a-8d4d-9639c7642160',
     'id': '38',
     'name': 'General',
     'type': 'folder'},
    {'children': [{'children': [{'date_added': '13354738436088296',
         'date_last_used': '13358616888589836',
         'guid': 'f6748ac3-64ee-420b-a2b3-480bb4123f5f',
         'id': '1202',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'Solving Data Science Interview Questions In SQL - Stratascatch',
         'type': 'url',
         'url': 'https://www.youtube.com/playlist?list=PLv6MQO1Zzdmq5w4YkdkWyW8AaWatSQ0kX'},
        {'date_added': '13355191511354479',
         'date_last_used': '13358617074690350',
         'guid': '127412e9-2b94-45ba-9a49-936246d3440c',
         'id': '1199',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'Crack Concepts - YouTube',
         'type': 'url',
         'url': 'https://www.youtube.com/@crackconcepts'},
        {'date_added': '13355191539114542',
         'date_last_used': '13358617086079330',
         'guid': 'f2228b77-3c98-4f60-ac17-1578756fa7f9',
         'id': '1201',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'Ankit Bansal - YouTube',
         'type': 'url',
         'url': 'https://www.youtube.com/@ankitbansal6'},
        {'date_added': '13355361192722989',
         'date_last_used': '13358617121086343',
         'guid': 'bb5a95ec-64f7-4397-b648-f331f689e1eb',
         'id': '1200',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'SQL Sundays | Tina Huang',
         'type': 'url',
         'url': 'https://www.youtube.com/playlist?list=PLVD3APpfd1tuXrXBWAntLx4tNaONro5dA'},
        {'date_added': '13355601677420020',
         'date_last_used': '13366503163876301',
         'guid': '69fb9b74-1ec6-4d0f-bfba-3973fd46fdbf',
         'id': '1203',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'QUERIES ASKED IN FAANG AND MNCS - YouTube',
         'type': 'url',
         'url': 'https://www.youtube.com/playlist?list=PLpDBa472H_1R_FXj0gwgrbddi0v5HJRbw'},
        {'date_added': '13365806980876571',
         'date_last_used': '0',
         'guid': '77fe4e78-7f85-4a51-93a7-ed6acbacc64f',
         'id': '1294',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'techTFQ | SQL Interview + Learning',
         'type': 'url',
         'url': 'https://www.youtube.com/@techTFQ/videos'}],
       'date_added': '13355191132587733',
       'date_last_used': '0',
       'date_modified': '13366752081405362',
       'guid': 'b8bf0d69-2796-4fd6-b13d-460ae0959a96',
       'id': '1198',
       'name': 'Youtube Playlists',
       'type': 'folder'},
      {'children': [{'date_added': '13357770706556337',
         'date_last_used': '13358121170099386',
         'guid': '1ce5b9d5-8434-47bd-b9ff-aab7b791077e',
         'id': '1229',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'SQL 50 | LeetCode',
         'type': 'url',
         'url': 'https://leetcode.com/studyplan/top-sql-50/'},
        {'date_added': '13356910607449098',
         'date_last_used': '13363710925444070',
         'guid': '556f6783-73c7-44d4-a308-ac136d7e131f',
         'id': '1215',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'SQL Interview Questions | DataLemur',
         'type': 'url',
         'url': 'https://datalemur.com/questions'},
        {'date_added': '13357107165491616',
         'date_last_used': '13366502029635840',
         'guid': '7157dc60-41b7-493c-be10-71bb6c00b6b5',
         'id': '1218',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'Interview Query | Interview Questions',
         'type': 'url',
         'url': 'https://www.interviewquery.com/questions'},
        {'date_added': '13279000248904670',
         'date_last_used': '13358035541144568',
         'guid': '91543142-2373-4920-a162-60c9c165ad4e',
         'id': '266',
         'name': 'SQL | StrataScratch',
         'type': 'url',
         'url': 'https://www.stratascratch.com/blog/categories/sql/'},
        {'date_added': '13354985113529028',
         'date_last_used': '13363710932535336',
         'guid': '47a9d5c0-9df6-495a-91d4-01332a9f26dc',
         'id': '1204',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'SQL | DataFord.io',
         'type': 'url',
         'url': 'https://dataford.io/sql'},
        {'date_added': '13279000256974287',
         'date_last_used': '13358035525845047',
         'guid': 'c8395b07-f8a9-4518-9181-3944a406beb7',
         'id': '267',
         'name': 'SQL Problems - LeetCode',
         'type': 'url',
         'url': 'https://leetcode.com/problemset/database/'},
        {'date_added': '13279000269264032',
         'date_last_used': '13358035638855607',
         'guid': '6bcf08ba-012b-44a9-9709-7dd3aa0b7a64',
         'id': '268',
         'name': 'Solve SQL | HackerRank',
         'type': 'url',
         'url': 'https://www.hackerrank.com/domains/sql'},
        {'date_added': '13354917824099750',
         'date_last_used': '13355700166314390',
         'guid': '5fcf14e7-3a17-4d08-8950-1a6c51e58c5f',
         'id': '1206',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'Data Engineer SQL | dataexpert.io',
         'type': 'url',
         'url': 'https://www.dataexpert.io/questions'},
        {'date_added': '13351204103325917',
         'date_last_used': '0',
         'guid': 'fc057867-68b8-4af3-8739-b62232c587d9',
         'id': '1167',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'Technical Questions - Analyst Builder',
         'type': 'url',
         'url': 'https://www.analystbuilder.com/questions'},
        {'date_added': '13359084390515650',
         'date_last_used': '0',
         'guid': '26157021-a894-4504-988e-b0b3efaa7634',
         'id': '1247',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'BigTechInterviews',
         'type': 'url',
         'url': 'https://app.bigtechinterviews.com/?listId=3gaililqYHxSiv3zZLHATl&pageSize=50'},
        {'date_added': '13366496915081688',
         'date_last_used': '0',
         'guid': 'eeeed8e3-8992-4b38-893b-e8e66c2700bf',
         'id': '1302',
         'meta_info': {'power_bookmark_meta': ''},
         'name': 'The Best Medium-Hard Data Analyst SQL Interview Questions - Quip',
         'type': 'url',
         'url': 'https://quip.com/2gwZArKuWk7W'}],
       'date_added': '13366066909982393',
       'date_last_used': '0',
       'date_modified': '13366496928017109',
       'guid': 'e3e3b41a-3727-44fe-bdbd-7822479f91ab',
       'id': '1296',
       'name': 'SQL Coding Practice',
       'type': 'folder'},
      {'date_added': '13358553116941911',
       'date_last_used': '13358616687089638',
       'guid': '5fc61725-d027-48d6-a0fa-e18dc22456b4',
       'id': '1237',
       'meta_info': {'power_bookmark_meta': ''},
       'name': 'Ultimate SQL Interview Guide For Data Scientists & Data Analysts',
       'type': 'url',
       'url': 'https://datalemur.com/blog/sql-interview-guide?utm_source=linkedin.com&utm_medium=social&utm_campaign=sql-interview-guide'},
      {'date_added': '13288383823098989',
       'date_last_used': '13366501458013794',
       'guid': '6a4ee28b-4234-4802-8403-f6df5681960e',
       'id': '497',
       'name': 'SQL-Interview-Prep-Question',
       'type': 'url',
       'url': 'https://github.com/Aafreen29/SQL-Interview-Prep-Question'},
      {'date_added': '13270988325000000',
       'date_last_used': '13350518098414538',
       'guid': '1e71917b-f085-4ee9-98a5-5e8acd3a272e',
       'id': '21',
       'name': 'The SQL Tutorial for Data Analysis | Basic SQL - Mode Analytics',
       'type': 'url',
       'url': 'https://mode.com/sql-tutorial/introduction-to-sql/'},
      {'date_added': '13351203473633666',
       'date_last_used': '13358616732312975',